final List<String> texts = [
"How to organize an effective football attack?",
"How to improve teamwork in basketball games?",
"How to control the rhythm in table tennis games?",
"What details should be paid attention to when serving in tennis?",
"How to improve the receiving and serving skills in badminton?",
"How to maintain a good rhythm in swimming competitions?",
"How to get off to a fast start in a sprint race?",
"How to maintain a steady speed in a cycling race?",
"How to effectively block the net in volleyball games?",
"How to accurately pitch in baseball games?",
"How to effectively defend in rugby games?",
"How to maintain possession of the ball in hockey games?",
"How to maintain balance in skiing competitions?",
"How to improve putting skills in golf games?",
"How to ensure safety when rock climbing?",
"How to perform difficult moves in skateboarding competitions?",
"How to maintain a consistent rhythm in rowing competitions?",
"How to effectively attack and defend in boxing competitions?",
"How to gain an advantage in judo competitions?",
"How to quickly defeat your opponent in wrestling competitions?",
"How to allocate physical strength in triathlons?",

"How to improve your basketball shooting accuracy?",
"How to optimize your serve in tennis?",
"How to block effectively in volleyball?",
"What is the best way to improve your backhand in table tennis?",
"How to hit a high-quality lob in badminton?",
"What are effective strategies to increase your marathon endurance?",
"How to improve your turning skills in swimming competitions?",
"How to reduce your putt error rate in golf competitions?",
"How to improve your hitting percentage in baseball games?",
"How to improve your ball control in hockey games?",
"How to improve your defensive skills in basketball games?",
"What are the ways to improve your long jump performance in track and field competitions?",
"How to improve your climbing ability in cycling competitions?",
"How to maintain a steady speed in skiing competitions?",
"How to improve your defensive skills in boxing competitions?",
"What are the effective ways to improve your hitting rate in archery competitions?",
"How to react quickly in fencing competitions?",
"How to master more complex moves in skateboarding competitions?",
"How to read the waves in surfing competitions?",
"How to improve your balance in gymnastics competitions?",
"How to improve your reaction speed in e-sports?",
"What are the ways to improve your sailing skills in sailing?",
"How to make a quick counterattack in basketball?",
"What are the serving techniques in table tennis?",
"How to improve your tennis serve speed?",
"How to hit the winning shot in badminton?",
"How to block effectively in volleyball?",
"How to maintain the best running posture in track and field competitions?",
"How to maintain a steady rhythm in long-distance running?",
"How to burst out the fastest speed in short-distance running?",
"How to improve the batting accuracy in baseball games?",
"How to effectively defend in football?",
"How to play man-to-man defense in basketball games?",
"How to improve your football dribbling skills?",
"How to improve your basketball shooting accuracy?",
"How to make an effective baseline attack in tennis games?",
"How to control the rhythm of the court in badminton games?",
"How to make an effective pass in volleyball games?",
"How to properly allocate physical strength in a marathon?",
"How to switch events in a triathlon? ",
"How to perform effective teamwork in basketball? ",
"How to perform effective corner kicks in football? ",
"How to improve your backhand technique in table tennis? ",
"How to perform effective volleys in tennis? ",
"How to perform effective short shots in badminton? ",
"How to perform effective serves in volleyball? ",
"How to improve your freestyle swimming skills? ",
];
